Added drc checks

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -22,6 +22,7 @@ jobs:
       - name: Run KiCad Action
         uses: ./
 
+  # Combine ERC and DRC check into one single job
   check-erc:
     runs-on: ubuntu-latest
     strategy:
@@ -51,6 +52,40 @@ jobs:
             exit 1
           fi
           if [[ "${{ matrix.result }}" == "success" && "${{ steps.erc_check.outcome }}" == "failure" ]]; then
+            echo "Expected success, but step failed!"
+            exit 1
+          fi
+        shell: bash
+
+  check-drc:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        test-name: ["drc-failure", "drc-success"]
+        include:
+          - test-name: drc-failure
+            pcb_file: tests/kicad-project-failure/kicad-project.kicad_pcb
+            result: failure
+          - test-name: drc-success
+            pcb_file: tests/kicad-project-success/kicad-project.kicad_pcb
+            result: success
+    steps:
+      - uses: actions/checkout@v4
+      - name: Run DRC check
+        id: drc_check
+        uses: ./
+        with:
+          run_drc: true
+          pcb_file: ${{ matrix.pcb_file }}
+        continue-on-error: true
+      - name: Verify Check File Step Result
+        run: |
+          if [[ "${{ matrix.result }}" == "failure" && "${{ steps.drc_check.outcome }}" != "failure" ]]; then
+            echo "Expected failure, but step succeeded!"
+            exit 1
+          fi
+          if [[ "${{ matrix.result }}" == "success" && "${{ steps.drc_check.outcome }}" == "failure" ]]; then
             echo "Expected success, but step failed!"
             exit 1
           fi
